config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :capsules do
    resources :bookings
    collection do
      get :search
    end
  end

  resources :bookings do
    resources :reviews
      member do
        patch :accept
        patch :decline
      end
  end

  resources :users do
    resources :bookings, only: %i[create]
  end

  resources :capsules, only: %i[destroy]
  resources :bookings, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :capsule
  belongs_to :user
  has_one :review, dependent: :destroy
  
end

app/models/capsule.rb
class Capsule < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo
  belongs_to :user


  validates :name, presence: true
  validates :year, presence: true
  validates :advices, presence: true
  validates :price_per_day, presence: true


  include PgSearch::Model
  pg_search_scope :search_by_name_and_years, against: %i[name description year],
                                             using: {
                                               tsearch: { prefix: true }
                                             }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :user, through: :booking
  validates :rating, presence: true
  validates :comment, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :capsules
  has_many :reviews, through: :bookings
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # proteger toutes les routes par defaut
  # before_action :authenticate_user!

  # before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  def after_sign_in_path_for(user)
    user_path(user)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  # def new
  #   @booking = Booking.new
  # end

  def create
    @capsule = Capsule.find(params[:capsule_id])
    @booking = Booking.new(booking_params)
    @booking.capsule = @capsule
    @booking.user = current_user
    @capsule.user_id = current_user.id
    @booking.statu = "en attente"
    if @booking.save!
      redirect_to user_path(@booking.user)
    else
      render 'capsules/show', status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    @user = current_user
    redirect_to user_path(@user), status: :see_other
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.statu = "confirmé"
    @booking.save

    if @booking.save!
      redirect_to user_path(@booking.user)
    else
      render 'capsules/show', status: :unprocessable_entity
    end
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.statu = "refusé"
    @booking.save
    if @booking.save!
      redirect_to user_path(@booking.user)
    else
      render 'capsules/show', status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end
end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController
  before_action :set_capsule, only: %i[show edit update destroy]

  def index
    @capsules = Capsule.all
    if params[:query]
      @capsules = Capsule.search_by_name_and_years(params[:query])
    else
      @capsules = Capsule.all
    end
  end

  def new
    @capsule = Capsule.new
  end

  def create
    @capsule = Capsule.new(capsule_params)
    @capsule.user = current_user
    if @capsule.save!
      redirect_to capsule_path(@capsule)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.new
    ratings = []
    @comments = []
    @capsule.reviews.each do |review|
      ratings << review.rating
      @comments << review.comment
    end
    @rating_number = ratings.count
    @rating_number > 0? @average_rating = (ratings.sum(0.0) / ratings.size).round(1) : @average_rating = 0
    @round_average_rating = @average_rating.round(0)
    @comments_number = @comments.count
  end

  def edit
  end

  def update
    if @capsule.update(capsule_params)
      redirect_to user_path(current_user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @capsule.destroy
    redirect_to user_path
  end

  private

  def set_capsule
    @capsule = Capsule.find(params[:id])
  end

  def capsule_params
    params.require(:capsule).permit(:name, :year, :advices, :price_per_day, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
    @capsules = Capsule.all
  end
  def search
    @capsules = Capsule.search(params[:query])
    render :home

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @review = Booking.find(params[:list_id])
    @review.booking = @review
    if @review.save
      redirect_to review_path(@list)
    else
      @booking = Booking.new
      render "reviews/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to review_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # before_action :set_user, only: [:show, :destroy]
  end

  # DETAIL SUR L'UTILISATEUR

  def show
    @user = current_user
    @bookings_received = Booking.joins(:capsule).where("capsules.user_id = ?", @user.id)
    @bookings_pending = @bookings_received.select { |booking| booking.statu == "pending" }
  end

  # CREATION D'UN NOUVEL UTILISATEUR

  def new
    @users = User.new
  end

  def create
    @users = User.new(user_params)
    @users.user = current_user
    if @users.save
      redirect_to users_path(@users)
    else
      render :new, status: :unprocessable_entity
    end
  end
  # UPDATE DU PROFIL UTILISATEUR

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    @users.update(user_params)
    redirect_to users_path
  end
  # DESTROY LE PROFIL UTILISATEUR

  def destroy
    @users = User.find(user_params)
    @users.destroy
    redirect_to users_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/capsules/_form_new_booking.html.erb
<%= simple_form_for [@capsule, @booking] do |f| %>
  <div data-controller="price-count">
    <%= f.input :start_date, label: "Date de départ", as: :string, input_html: { data: { controller: "datepicker", price_count_target: "start" } } %>
    <%= f.input :end_date, label: "Date de retour", as: :string, input_html: { data: { controller: "datepicker", price_count_target: "end", action: "change->price-count#totalPrice" } } %>
    <%= f.hidden_field :total_price, id: "total_booking_price" %>
    <%= f.submit 'Réserver', class: "reserve-btn" %>
  </div>
<% end %>

app/views/capsules/edit.html.erb
<h1>Modifier votre capsule</h1>
<div id="capsule-form">
  <%= simple_form_for @capsule do |f| %>
    <%= f.input :name, label: "Nom de la capsule" %>
    <%= f.input :year, label: "Année" %>
    <%= f.input :description, label: "Description", as: :text %>
    <%= f.input :advices, label: "Conseils", as: :text %>
    <%= f.input :price_per_day, label: "Prix par jour" %>
    <%= f.input :photo, label: "Image", as: :file %>
    <%#= f.input :photos, label: "Autres photos", as: :file, input_html: { multiple: true } %>

    <%= f.button :submit, "Enregistrer mes modifications", class: "capsule-form-button" %>
  <% end %>
</div>

app/views/capsules/index.html.erb
<!-- List of Capsules -->
<div class='main-capsule-container'>
  <h1 class="capsules-title">Liste des [apsu[es</h1>
  <div class="container capsules-container">
    <% @capsules.each do |capsule| %>
      <div class="capsule-card">
        <%= cl_image_tag capsule.photo.key, class: "capsule-image" %>
        <div class="capsule-card-infos">
          <div class="capsule-details">
            <h2 class="capsule-name"><%= capsule.name %></h2>
            <p class="capsule-year"><%= capsule.year %></p>
          </div>
          <div>
            <p class="capsule-description"><%= capsule.description %></p>
          </div>
            <div class="footer-card">
              <h2 class="card-trip-pricing">TARIF JOURNALIER <%= capsule.price_per_day %>€</h2>
              <%= link_to 'Show', capsule_path(capsule), class: "capsule-show-link" %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/capsules/new.html.erb
<h1>Ajoutez votre capsule au catalogue</h1>
<div id="capsule-form">
  <%= simple_form_for @capsule do |f| %>
    <%= f.input :name, label: "Nom de la capsule" %>
    <%= f.input :year, label: "Année" %>
    <%= f.input :description, label: "Description", as: :text %>
    <%= f.input :advices, label: "Conseils", as: :text %>
    <%= f.input :price_per_day, label: "Prix par jour" %>
    <%= f.input :photo, label: "Image", as: :file %>
    <%#= f.input :photos, label: "Autres photos", as: :file, input_html: { multiple: true } %>

    <%= f.button :submit, "Proposer ma capsule", class: "capsule-form-button" %>
  <% end %>
</div>

app/views/capsules/show.html.erb
<h1><%= @capsule.name %> - <%= @capsule.year %></h1>
<div class="container_show d-flex">
  <div id="capsule-top">
    <div class="capsule-show-image">
        <%= cl_image_tag @capsule.photo.key %>
    </div>
    <h3 class="mb-5"><%= @capsule.description %></h3>
    <div id="average_rating">
      <p>Note moyenne :
      <%= @average_rating %> / 5
      <%  @round_average_rating.times do  %>
        <i class="fa-solid fa-star" style="color: #f2b407;"></i>
      <% end %>
      <%  (5-@round_average_rating).times do  %>
        <i class="fa-regular fa-star" style="color: #f2b407;"></i>
      <% end %>
      - <%= @comments_number %> commentaire<%= "s" if @comments_number > 1 %>
      </p>
    </div>

    <div class="d-flex justify-content-between mt-4">
      <div id="conseil" class="border px-3">
        <h4 class="text-center">Nos conseils</h4>
        <p><%= @capsule.advices %></p>
      </div>
      <div class="cadre-gris">
        <h4>Tarif</h4>
            <span id="price-per-day" class="price-value"><%= @capsule.price_per_day %></span>
            <span class="price-unit">€/j</span>
          </p>
      </div>
    </div>
  </div>

  <div id="booking">
    <h2>Réservez maintenant ce voyage temporel</h2>
    <div class="m-auto">
      <%= render 'form_new_booking' %>
      <div class="d-flex justify-content-between mt-3 ms-3 me-3">
        <p id="count-price"></p>
        <p id="total-price"></p>
      </div>
      <div class="d-flex justify-content-between ms-3 me-3">
        <p id="title-service"></p>
        <p id="service-price"></p>
      </div>
      <div class="d-flex justify-content-between mt-3 ms-3 me-3" id="title-price">
      </div>
    </div>
  </div>
</div>
<%# commmentaires des users %>
<div id="comments" class="container_show">
  <h3 class="mb-4">Tous les commentaires</h3>
  <%= "Aucun commentaire n'a encore été déposé sur cette capsule." if @comments_number == 0 %>
  <div class="comment-list">
    <div class="comments-wrapper">
    <% @capsule.reviews.each do |review| %>
      <div class="comment-item">
        <div class="rating">
          <%  review.rating.round(0).times do  %>
            <i class="fa-solid fa-star" style="color: #f2b407;"></i>
          <% end %>
          <%  (5-review.rating.round(0)).times do  %>
            <i class="fa-regular fa-star" style="color: #f2b407;"></i>
          <% end %>
        </div>
        <p class="comment-text">"<%= review.comment %>"</p>
        <div class="comment-author">
          <strong><%= review.booking.user.first_name %> <%= review.booking.user.last_name %></strong>
          <span class="text-secondary">(<%= review.booking.start_date.day %>/<%= review.booking.start_date.month %>/<%= review.booking.start_date.year %>)</span>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapsuleCorp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<header class="header">
  <video class="header-video" autoplay muted loop>
    <source src="<%= video_path('/videos/header-video.mp4') %>" type="video/mp4">
  </video>

  <div class="header-overlay"></div>

    <div class="header-content">
      <h1 class="header-title">[apsu]e <strong>corp</strong></h1>
      <p class="header-subtitle">Travelling without moving</p>


<div class=main-search>
    <div class="search-form-control">
      <%= form_with url: capsules_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "control",
          placeholder:"le voyage commence ici"%>
          <%= submit_tag "RECHERCHE", class: "btn btn-primary" %>
        </div>

          <p class="header-description"><em>passionné de voyages, d'histoire ou tout simplement curieux<br>
          venez revivre les evenements qui ont marqué l'Histoire</em></p>
        </div>

      <% end %>
  </div>
</div>
</header>


<!-- List of Capsules -->
<div class='main-capsule-container'>
  <h1 class="capsules-title">les [apsu]es</h1>
  <p>Concert mythique, évenement historique, bataille célèbre, rencontre sportive...<br>
  <strong>Soyez présent </strong>(ou passé)</p>
    </div>
  <div class="container capsules-container">
    <% @capsules.each do |capsule| %>
      <div class="capsule-card">
        <%= cl_image_tag capsule.photo.key, class: "capsule-image" %>
        <div class="capsule-card-infos">
          <div class="capsule-details">
            <h2 class="capsule-name"><%= capsule.name %></h2>
            <p class="capsule-year"><%= capsule.year %></p>
          </div>
          <div>
            <p class="capsule-description"><%= capsule.description %></p>
          </div>
          <h2 class="card-trip-pricing">Tarif par jour : <%= capsule.price_per_day %>€</h2>
          <%= link_to 'Show', capsule_path(capsule), class: "capsule-show-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/capsulcorpo/?hl=fr"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/CapsuleCorpStudio/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/capsulecorpstd"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/company/capsule-corporation-ltd/?originalSubdomain=fr"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Capsule Corp is a production of the Clash of Buzz team !
  </div>
</div>

app/views/shared/_navbar.html.erb
  <!-- Navbar -->
<div class="navbar">
    <div class="container-nav">
      <div class='header-logo'>
        <%= link_to image_tag("logoCapCorp.png", class: "navbar-logo"), root_path %>
      </div>

      <ul class="navbar-menu">
        <%# <li class="nav-item">
          <%= link_to "SEARCH", search_capsules_path, class: "nav-link" %>
        <%# </li> %>
        <% if current_user %>
          <li class="d-none"><%= link_to "SE CONNECTER", user_session_path, class: "nav-link" %></li>
        <% else %>
          <li><%= link_to "SE CONNECTER", user_session_path, class: "nav-link" %></li>
        <% end %>
        <li class="nav-item dropdown">
          <% if current_user %>
            <%= link_to user_path(current_user) do %>
              <%= cl_image_tag current_user.photo.key, class: "avatar-bordered" %>
            <% end %>
            <div class="dropdown-menu">
              <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item" %>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

app/views/users/index.html.erb
<h1>VIEW USERS</h1>
<%# je vous laisse faire le front les potos %>

    "imports": {
      "stimulus": "https://unpkg.com/@hotwired/stimulus/dist/stimulus.js",
      <!-- [...] -->
    }
  

app/views/users/new.html.erb
<h1>CREER UN NOUVEL USER </h1>
<%# JE VOUS LAISSE FAIRE LE FRONT LES POTOS %>

app/views/users/show.html.erb
<div class="container-user-page">
  <%= link_to "Mon profil", "#profil", class: "navigate" %>
  <%= link_to "Mes voyages", "#mes-voyages", class: "navigate" %>
  <%= link_to "Vos capsules", "#capsules", class: "navigate" %>
  <%= link_to "Réservations à confirmer", "#a-confirmer", class: "navigate" %>
  <%= link_to "Réservations confirmées", "#commandes-confirmees", class: "navigate" %>
</div>

<h3 id="profil">MON PROFIL UTILISATEUR</h3>
<div class="container_profil">
  <div class="identity">
    <div class="avatar-container">
      <%= cl_image_tag current_user.photo.key, class: "avatar-large" %>
    </div>

    <div class="informations">
      <div class="full-username">
          <p class="first-name">Prenom: <%= @user.first_name %></p>
          <p class="last-name">Nom: <%= @user.last_name %></p>
          <p class="email" >Email: <%= @user.email %></p>
      </div>
    </div>
  </div>

<%# on affiche toutes les voyages réservés par l'utilisateur %>
<div id="mes-voyages">
  <h3 class="booking-title">Vos voyages</h1>
  <div class="booking-container">
    <% @user.bookings.each do |booking| %>
      <div class="booking-card">
        <%= cl_image_tag booking.capsule.photo.key, class: "booking-image" %>
        <div class="booking-card-infos">
          <div class="booking-details">
            <h2 class="booking-name"><%= booking.capsule.name %></h2>
            <p class="booking-year"><%= booking.capsule.year %></p>
          </div>
          <div>
            <h4>Vos dates de voyage</h4>
            <p class="booking-description"><%= booking.start_date.strftime("%d-%m-%Y") %></p>
            <p class="booking-description"><%= booking.end_date.strftime("%d-%m-%Y") %></p>
          </div>
          <% if booking.statu == "confirmé" %>
            <div>
              <p class="statut-accept"><strong><%= booking.statu.capitalize %></strong></p>
            </div>
          <% elsif booking.statu == "en attente" %>
            <div>
              <p class="statut-pending"><strong><%= booking.statu.capitalize %></strong></p>
            </div>
          <% elsif booking.statu == "refusé" %>
            <div>
              <p class="statut-decline"><strong><%= booking.statu.capitalize %></strong></p>
            </div>
          <% end %>
          <h2 class="card-trip-pricing">Montant total : <%= booking.total_price %>€</h2>
          <%= link_to "Annuler ma réservation", booking_path(booking), class: "booking-delete-link",
          data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr de supprimer cette réservation ? AUCUN REMBOURSEMENT, NADA !"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%# on affiche toutes les capsules crées par l'utilisateur %>
<div id="capsules">
  <h3 class="booking-title">Les capsules que vous proposez</h1>
  <% if @user.capsules.length == 0 %>
    <p class="text-danger text-center mb-5">Vous ne proposez encore aucune capsule</p>
  <% else %>
    <div class="container booking-container">
      <% @user.capsules.each do |capsule| %>
        <div class="booking-card">
          <%= cl_image_tag capsule.photo.key, class: "booking-image" %>
          <div class="booking-card-infos">
            <div class="booking-details">
              <h2 class="booking-name"><%= capsule.name %></h2>
              <p class="booking-year"><%= capsule.year %></p>
            </div>
            <h2 class="card-trip-pricing">Le tarif par jour : <%= capsule.price_per_day %>€</h2>
            <%= link_to "Modifier cette capsule", edit_capsule_path(capsule), class: "booking-edit-link" %>
            <%= link_to "Supprimer cette capsule", capsule_path(capsule), class: "booking-delete-link",
            data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr de supprimer cette capsule de votre catalogue ?"} %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%# on affiche toutes les commandes passées auprès de l'owner de la capsule et qui sont attente %>
<div class="container-product" id="a-confirmer">
  <h3 class="booking-title">Les réservations en attente de votre confirmation</h1>
  <% @user.capsules.each do |capsule| %>
    <% capsule.bookings.each do |booking| %>
      <% if booking.statu == "en attente" %>
        <div class="card-product">
          <%= cl_image_tag booking.capsule.photo.key %>
          <div class="card-product-infos" id="details">
            <h4><%= booking.capsule.name %></h4>
            <p>Réservation faite par</h4>
            <h6><%= booking.user.first_name %> <%= booking.user.last_name %></h6>
            <p>Dates de la réservation</h4>
            <h6>du <%= booking.start_date.strftime("%d-%m-%Y") %> au <%= booking.end_date.strftime("%d-%m-%Y") %></h6>
          </div>
          <div class="card-product-infos" id="price">
            <h4>Prix total de la réservation</h4>
            <h5><%= booking.total_price %>€</h5>
          </div>
          <div class="card-product-infos" id="buttons">
            <h6><%= button_to "Accepter", accept_booking_path(booking), method: :patch, class: "capsule-confirm-link" %></h6>
            <h6><%= button_to "Refuser", decline_booking_path(booking), method: :patch, class: "capsule-confirm-link" %></h6>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<%# on affiche toutes les commandes passées auprès de l'utilisateur %>
<div class="container-product" id="commandes-confirmees">
  <h3 class="booking-title">Les commandes que vous avez confirmées</h1>
  <% if @bookings_received.length == 0 %>
    <p class="text-danger text-center mb-5">Vous n'avez encore confirmé aucune commande</p>
  <% else %>
    <% @user.capsules.each do |capsule| %>
      <% capsule.bookings.each do |booking| %>
        <% if booking.statu == "confirmé" %>
          <div class="card-product">
            <%= cl_image_tag booking.capsule.photo.key %>
            <div class="card-product-infos" id="details">
              <h4><%= booking.capsule.name %></h4>
              <p>Réservation faite par</h4>
              <h6><%= booking.user.first_name %> <%= booking.user.last_name %></h6>
              <p>Dates de la réservation</h4>
              <h6>du <%= booking.start_date.strftime("%d-%m-%Y") %> au <%= booking.end_date.strftime("%d-%m-%Y") %></h6>
            </div>
            <div class="card-product-infos" id="price">
              <h4>Prix total de la réservation</h4>
              <h5><%= booking.total_price %>€</h5>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>
  <%# on affiche toutes les commandes refusées par le owner %>
<div class="container-product" id="commandes-refusées">
  <h3 class="booking-title">Les commandes que vous avez refusées</h1>
  <% if @bookings_received.length == 0 %>
    <p class="text-danger text-center mb-5">Vous n'avez refusé aucune commande</p>
  <% else %>
    <% @user.capsules.each do |capsule| %>
      <% capsule.bookings.each do |booking| %>
        <% if booking.statu == "refusé" %>
          <div class="card-product">
            <%= cl_image_tag booking.capsule.photo.key %>
            <div class="card-product-infos" id="details">
              <h4><%= booking.capsule.name %></h4>
              <p>Réservation faite par</h4>
              <h6><%= booking.user.first_name %> <%= booking.user.last_name %></h6>
              <p>Dates de la réservation</h4>
              <h6>du <%= booking.start_date.strftime("%d-%m-%Y") %> au <%= booking.end_date.strftime("%d-%m-%Y") %></h6>
            </div>
            <div class="card-product-infos" id="price">
              <h4>Prix total de la réservation</h4>
              <h5><%= booking.total_price %>€</h5>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="create-capsule-button-container">
  <%= link_to "Créer une capsule", new_capsule_path, class: "create-capsule-button" %>
</div>